---
# Source: quay-enterprise/templates/01_SpeedTest_project.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: speedtest

---
# Source: salty/templates/02_SpeedTest_Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: "{{ .Values.image.source }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
