apiVersion: v1
kind: Secret
metadata:
  name: apicast-configuration-url-secret
type: kubernetes.io/basic-auth
stringData:
  password: "https://{{.Values.THREE_SCALE_TOKEN}}@{{.Values.OPENSHIFT_URL}}"
