apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.APICAST_NAME}}"
spec:
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deploymentconfig: "{{.Values.APICAST_NAME}}"
